[project]
name = "wsbackend-fabrica25-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.6",
    "psycopg[binary]>=3.2.10",
    "requests>=2.32.5",
]
