# Generated by Django 5.2.6 on 2025-09-13 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Device model name', max_length=100)),
                ('manufacturer', models.CharField(help_text='Device manufacturer', max_length=100)),
                ('serial_number', models.CharField(help_text='Device serial number', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
