# Generated by Django 5.2.6 on 2025-09-13 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(help_text='CNPJ in format XX.XXX.XXX/XXXX-XX', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ must be in format XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
                ('company_name', models.CharField(help_text='Legal company name (Razão Social)', max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(help_text='Customer email address', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
